---

  env:
    node: true
    jest: true

  plugins:
    - jest
    - babel
    - flowtype

  parser: babel-eslint

  extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:flowtype/recommended'

  rules:
    no-console: 0